dockerfile

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -62,6 +62,20 @@ jobs:
           rm: false
           debug: true
 
+      - name: Ensure Docker is installed
+        uses: appleboy/ssh-action@v1.1.0
+        with:
+          host: ${{ secrets.SERVER_IP }}
+          username: ${{ secrets.SERVER_USER }}
+          key: ${{ secrets.SERVER_SSH_KEY }}
+          script: |
+            if ! command -v docker >/dev/null 2>&1; then
+              echo "Docker not found. Installing..."
+              curl -fsSL https://get.docker.com | sudo sh
+            else
+              echo "Docker already installed."
+            fi
+
       - name: Deploy container
         uses: appleboy/ssh-action@v1.1.0
         with:
@@ -69,10 +83,10 @@ jobs:
           username: ${{ secrets.SERVER_USER }}
           key: ${{ secrets.SERVER_SSH_KEY }}
           script: |
-            docker pull davidburnazyan/ci-cd:latest
-            docker stop cd-ci || true
-            docker rm cd-ci || true
-            docker run -d --name cd-ci -p 3000:3000 davidburnazyan/ci-cd:latest
+            sudo docker pull davidburnazyan/ci-cd:latest
+            sudo docker stop cd-ci || true
+            sudo docker rm cd-ci || true
+            sudo docker run -d --name cd-ci -p 3000:3000 davidburnazyan/ci-cd:latest
 
       - name: Install production modules & restart PM2
         uses: appleboy/ssh-action@v1.1.0
